# Generated by Django 2.1.5 on 2019-02-16 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('effective_to_date', models.DateField(verbose_name='date')),
                ('amount', models.FloatField(default=0.0, verbose_name='amount')),
                ('comment', models.TextField(default='null', verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='DailySpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 16, 13, 51, 45, 494146))),
                ('spending', models.FloatField(default=0.0)),
            ],
        ),
    ]
