# Generated by Django 2.1.5 on 2019-02-09 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentFlow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentflows',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='currentflows',
            name='comment',
            field=models.TextField(default='null', verbose_name='comment'),
        ),
        migrations.AddField(
            model_name='currentflows',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentflows',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='time'),
            preserve_default=False,
        ),
    ]
