# Generated by Django 2.1.5 on 2019-02-11 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentFlow', '0002_auto_20190210_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentflows',
            name='effective_to_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
