# Generated by Django 2.1.5 on 2019-02-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentFlow', '0003_currentflows_effective_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('cost', models.FloatField(default=0.0, verbose_name='cost')),
            ],
        ),
    ]
