# Generated by Django 2.1.5 on 2019-02-12 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentFlow', '0005_auto_20190212_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyspending',
            name='cost',
        ),
        migrations.AddField(
            model_name='dailyspending',
            name='spending',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailyspending',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 12, 15, 30, 12, 570167)),
        ),
    ]
