# Generated by Django 2.1.5 on 2019-02-24 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CurrentFlow', '0007_auto_20190212_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(default='null', verbose_name='user_name')),
                ('password', models.TextField(default='null', verbose_name='password')),
                ('auto_login', models.BooleanField(default=False, verbose_name='auto_log_in')),
                ('last_login_time', models.DateTimeField(verbose_name='last_login_time')),
                ('email_address', models.TextField(default='null', verbose_name='email_address')),
            ],
        ),
        migrations.AddField(
            model_name='currentflows',
            name='user_name',
            field=models.TextField(default='null', verbose_name='user_name'),
        ),
        migrations.AddField(
            model_name='dailyspending',
            name='user_name',
            field=models.TextField(default='null', verbose_name='user_name'),
        ),
        migrations.AlterField(
            model_name='currentflows',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dailyspending',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 24, 12, 34, 43, 764989)),
        ),
    ]
